version: '3'

services:
  senao_project_mysql:
    image: zakilu/senao_project:mysql_latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always

  senao_project_app:
    image: zakilu/senao_project:senao_latest
    ports:
      - "5000:5000"
    depends_on:
      - senao_project_mysql
    command: ["./wait-for-it.sh", "senao_project_mysql:3306", "--", "python", "app.py"]
    restart: always


